language: node_js
node_js:
  - "6"
  - "4"
services:
  - postgresql
before_script:
  - psql -c 'create database travis;' -U postgres -w
  - psql -c 'create database testing;' -U postgres -w
  - psql -f 'scripttest.sql'
