version: '2'
services:
  db:
    image: postgres:9-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: hello
      POSTGRES_USER: nidhi
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
